vsphere_server     = "10.0.0.9"
vsphere_user       = "Administrator@vsphere.local"
vsphere_password   = "*******"
vcenter_license    = "*******"
datacenter         = "XZLabDatacenter"
datastore          = "iSCSI-Datastore"
cluster            = "XZLabCluster"
network_name       = "vData"
